Create a function change of basis matrix taking as argument two lists of vectors, origin
and destination, and returning the change of basis matrix Pdestination←origin. The function
will ensure that the lists are indeed bases and that operations are indeed possible.
As an illustration of the fact that your function does what is it meant to do, work through
Problem 3 in the mathematical part using this function.

$$X = \begin{bmatrix}1 \\
0 \\
-1
\end{bmatrix}$$

In [1]:
X= matrix(c(1,0,-1),nr = 3)
X


[,1]
[1,]  1  
[2,]  0  
[3,] -1

$$B = \begin{bmatrix}1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}$$

$$C = \begin{bmatrix}1 & 0 & 0\\
1 & 1 & 0\\
1 & 1 & 1
\end{bmatrix}$$

In [69]:
V1=  matrix(c(1,0,0),nr = 3)
V2= matrix(c(0,1,0),nr = 3)
V3= matrix(c(0,0,1),nr = 3)

W1=  matrix(c(1,1,1),nr = 3)
W2= matrix(c(0,1,1),nr = 3)
W3= matrix(c(0,0,1),nr = 3)

In [70]:
B = matrix(c(V1,V2,V3), nr = 3)
B
#combination of basis vector
C = matrix(c(W1,W2,W3), nr = 3)
C


[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 1    1    0   
[3,] 1    1    1

### Change Basis Matrix function

In [101]:
Change_Basis_Matrix <- function(matrixD , matrixO ){
    if( ncol(matrixO) == 1){
        POD = solve(matrixD,matrixO)
    }
    else{

for(num in 1:ncol(matrixD)){
Ox = matrix(c(matrixO[,num]))
Ox
x = solve(matrixD,Ox)
print(x)
if(num == 1){
POD <- matrix (x) 
}else {
POD = matrix(c(POD,x),ncol = num)
}
  }
        }
 
return (POD)   
}


#### Find the changes in Basis of the matrix 
Find the change of basis matrix PC←B from B to C.

Find the change of basis matrix PB←C from C to B.

In [100]:
Change_Basis_Matrix(C,B)

     [,1]
[1,]    1
[2,]   -1
[3,]    0
     [,1]
[1,]    0
[2,]    1
[3,]   -1
     [,1]
[1,]    0
[2,]    0
[3,]    1


[,1] [,2] [,3]
[1,]  1    0   0   
[2,] -1    1   0   
[3,]  0   -1   1

In [102]:
Change_Basis_Matrix(B,C)

     [,1]
[1,]    1
[2,]    1
[3,]    1
     [,1]
[1,]    0
[2,]    1
[3,]    1
     [,1]
[1,]    0
[2,]    0
[3,]    1


[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 1    1    0   
[3,] 1    1    1

#### Find the changes in Basis of the matrix 
Find the coordinate vectors [x]B and [x]C of x with respect to the bases (of R3) B and C, respectively.

In [103]:
Change_Basis_Matrix(B,X)

[,1]
[1,]  1  
[2,]  0  
[3,] -1

In [104]:
Change_Basis_Matrix(C,X)

[,1]
[1,]  1  
[2,] -1  
[3,] -1

#### Find the change of basis matrix PC←B from B to C to compute [X]C and compare to your answer to [X]C

In [106]:
Test = Change_Basis_Matrix(C,B) %*% Change_Basis_Matrix(B,X)
Test
Test == Change_Basis_Matrix(C,X)

     [,1]
[1,]    1
[2,]   -1
[3,]    0
     [,1]
[1,]    0
[2,]    1
[3,]   -1
     [,1]
[1,]    0
[2,]    0
[3,]    1


[,1]
[1,]  1  
[2,] -1  
[3,] -1

[,1]
[1,] TRUE
[2,] TRUE
[3,] TRUE