# Assignment 5: `Computer part`
### Student: Hoang Bao Long Vo - A01 Math2740 - 7924848


Create a jupyter notebook or RMarkdown file in which you verify your answers to the
questions in Problems 1 and 3 in the Written part of Assignment 5 using R instead of
computing by hand. Feel free to use existing R functions or work through the computations
step by step, but make sure the results appear clearly in the same way as they would if you
were working through the exercises by hand. (That is, if a function returns a list, do not
just display the list but display explicitly the element in the list that answers the question
at hand.

$$A = \begin{bmatrix}1 & 1\\
0 & 0
\end{bmatrix}$$


In [8]:
A <- matrix(c(1,0,1,0),nr = 2, nc = 2)
A

[,1] [,2]
[1,] 1    1   
[2,] 0    0

In [9]:
A.svd <- svd(A)
A.svd

$d
[1] 1.414214 0.000000

$u
     [,1] [,2]
[1,]    1    0
[2,]    0    1

$v
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068

### Doing Step by Step 

Function

In [58]:
svd_func <- function(matrix){
   print( "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix ")
print(matrix) 
print(t(matrix))
MTM <- t(matrix) %*% matrix
MT <- t(matrix)
print( "this is the result of the multiplication of transpose matrix and matrix" )
print(MTM)

MTM.lamda <- eigen(MTM)
print(MTM.lamda)
V <- MTM.lamda$vectors
print("matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix ")
       print("V")
print(V)
    
    
print( "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix ")
MMT <- matrix %*% t(matrix)
print( "this is the result of the multiplication of matrix and t(matrix)" )
print(MMT)
MMT.lamda <- eigen(MMT)
print(MMT.lamda)
U <- -MMT.lamda$vectors
    print("U")
print(U)
    
print("matrix r is the combination of sigular values  ")
R <- sqrt(MMT.lamda$values)
    print(R)  
R <- R * diag(length(R))
       print("R")
print(R)    
   
    
svd_matrix <- U %*% R %*% t(V)
    
print("SVD function = U + R + t(V) ")
print("$U ")
print(U)
 print("$R ")
print(R)   
    print("$V")
print(V)
    print("combination of SVD function return the original")
return (svd_matrix)    
}


In [61]:
print("MatrixA step by step")
svd_func(A)

[1] "MatrixA step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2]
[1,]    1    1
[2,]    0    0
     [,1] [,2]
[1,]    1    0
[2,]    1    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2]
[1,]    1    1
[2,]    1    1
eigen() decomposition
$values
[1] 2 0

$vectors
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the result of the multiplication of matrix and t(matrix)"
     [,1] [,2]
[1,]    2    0
[2,]    0    0
eigen() decomposition
$values
[1] 2 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[1] "U"
     [

[,1] [,2]
[1,] 1    1   
[2,] 0    0

# B

$$B = \begin{bmatrix}-2 & 0\\
0 & 0
\end{bmatrix}$$


In [11]:
B <- matrix(c(-2,0,0,0),nr = 2, nc = 2)
B

[,1] [,2]
[1,] -2   0   
[2,]  0   0

In [12]:
B.svd <- svd(B)
B.svd

$d
[1] 2 0

$u
     [,1] [,2]
[1,]    1    0
[2,]    0    1

$v
     [,1] [,2]
[1,]   -1    0
[2,]    0    1

### Step by step

In [62]:
print("Matrix B step by step")
svd_func(B)

[1] "Matrix B step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2]
[1,]   -2    0
[2,]    0    0
     [,1] [,2]
[1,]   -2    0
[2,]    0    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2]
[1,]    4    0
[2,]    0    0
eigen() decomposition
$values
[1] 4 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the result of the multiplication of matrix and t(matrix)"
     [,1] [,2]
[1,]    4    0
[2,]    0    0
eigen() decomposition
$values
[1] 4 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[1] "U"
     [,1] [,2]
[1,]    1    0
[2,]    0    1
[1] "matrix r is the combi

[,1] [,2]
[1,] -2   0   
[2,]  0   0

# C

$$C = \begin{bmatrix}2 & 0& 1\\
0 & 1 &0
\end{bmatrix}$$


In [17]:
C <- matrix(c(2,0,0,2,1,0),nr = 2, nc = 3)
C


[,1] [,2] [,3]
[1,] 2    0    1   
[2,] 0    2    0

In [18]:
svd_func3 <- function(matrix){
   print( "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix ")
print(matrix) 
print(t(matrix))
MTM <- t(matrix) %*% matrix
MT <- t(matrix)
print( "this is the result of the multiplication of transpose matrix and matrix" )
print(MTM)

MTM.lamda <- eigen(MTM)
print(MTM.lamda)
V <- -MTM.lamda$vectors
    V[,1] <- V[,1] * -1


print("matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix ")
       print("V")
print(V)
    
    
print( "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix ")
MMT <- matrix %*% t(matrix)
print( "this is the result of the multiplication of matrix and t(matrix)" )
print(MMT)
MMT.lamda <- eigen(MMT)
print(MMT.lamda)
U <- -MMT.lamda$vectors
    print("U")
print(U)
    
print("matrix r is the combination of sigular values  ")
R <- sqrt(MMT.lamda$values)
    print(R)  
R <- R * diag(length(R))
R = matrix (c(R,0,0), nr = 2, nc = 3)    
       print("R")
print(R)    
    
svd_matrix <- U %*% R %*% t(V)
    
print("#SVD function = U + R + t(V) ")
print("$U ")
print(U)
 print("$R ")
print(R)   
    print("$V")
print(V)
    print("# combination of SVD function return the original")
   print(V[,1:2])
return (svd_matrix)    
}


In [63]:
print("Matrix C step by step")
svd_func3 (C)

[1] "Matrix C step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2] [,3]
[1,]    2    0    1
[2,]    0    2    0
     [,1] [,2]
[1,]    2    0
[2,]    0    2
[3,]    1    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2] [,3]
[1,]    4    0    2
[2,]    0    4    0
[3,]    2    0    1
eigen() decomposition
$values
[1] 5.000000e+00 4.000000e+00 3.552714e-15

$vectors
          [,1] [,2]       [,3]
[1,] 0.8944272    0  0.4472136
[2,] 0.0000000   -1  0.0000000
[3,] 0.4472136    0 -0.8944272

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
          [,1] [,2]       [,3]
[1,] 0.8944272    0 -0.4472136
[2,] 0.0000000    1  0.0000000
[3,] 0.4472136    0  0.8944272
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the result of the 

[,1] [,2] [,3]
[1,] 2    0    1   
[2,] 0    2    0

# Part 2: PSEUDOINVERSE

In [64]:
pseudo_func <- function(matrix){
   print( "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix ")
print(matrix) 
print(t(matrix))
MTM <- t(matrix) %*% matrix
MT <- t(matrix)
print( "this is the result of the multiplication of transpose matrix and matrix" )
print(MTM)

MTM.lamda <- eigen(MTM)
print(MTM.lamda)
V <- MTM.lamda$vectors
print("matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix ")
       print("V")
print(V)
    
    
print( "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix ")
MMT <- matrix %*% t(matrix)
print( "this is the result of the multiplication of matrix and t(matrix)" )
print(MMT)
MMT.lamda <- eigen(MMT)
print(MMT.lamda)
U <- -MMT.lamda$vectors
    print("U")
print(U)
    
print("matrix r is the combination of sigular values  ")
R <- sqrt(MMT.lamda$values)
    print(R) 
    

   print("pseudoinvese of R (R+)")   
R_pseu <- R * diag(length(R))
R_pseu[1,1] <-    1/ R_pseu[1,1]
       print(R_pseu)    

    
    
    
  
    
pseudo_matrix <- U %*% R_pseu %*% t(V)
    
print("SVD function = U + R + t(V) ")
print("$U ")
print(U)
 print("$R+ ")
print(R_pseu)   
    print("$V")
print(V)
    print("combination of SVD function return the original")
return (pseudo_matrix)    
}


In [67]:
print("Matrix A pseudo-inverse step by step")
pseudo_func(A)

[1] "Matrix A pseudo-inverse step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2]
[1,]    1    1
[2,]    0    0
     [,1] [,2]
[1,]    1    0
[2,]    1    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2]
[1,]    1    1
[2,]    1    1
eigen() decomposition
$values
[1] 2 0

$vectors
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the result of the multiplication of matrix and t(matrix)"
     [,1] [,2]
[1,]    2    0
[2,]    0    0
eigen() decomposition
$values
[1] 2 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[,1] [,2]
[1,] 0.5  0.5 
[2,] 0.0  0.0

In [68]:
print("Matrix B pseudo-inverse step by step")
pseudo_func(B)

[1] "Matrix B pseudo-inverse step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2]
[1,]   -2    0
[2,]    0    0
     [,1] [,2]
[1,]   -2    0
[2,]    0    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2]
[1,]    4    0
[2,]    0    0
eigen() decomposition
$values
[1] 4 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the result of the multiplication of matrix and t(matrix)"
     [,1] [,2]
[1,]    4    0
[2,]    0    0
eigen() decomposition
$values
[1] 4 0

$vectors
     [,1] [,2]
[1,]   -1    0
[2,]    0   -1

[1] "U"
     [,1] [,2]
[1,]    1    0
[2,]    0    1
[1] "matrix

[,1] [,2]
[1,] -0.5 0   
[2,]  0.0 0

In [66]:
pseudo_func3 <- function(matrix){
   print( "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix ")
print(matrix) 
print(t(matrix))
MTM <- t(matrix) %*% matrix
MT <- t(matrix)
print( "this is the result of the multiplication of transpose matrix and matrix" )
print(MTM)

MTM.lamda <- eigen(MTM)
print(MTM.lamda)
V <- -MTM.lamda$vectors
    V[,1] <- V[,1] * -1


print("matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix ")
       print("V")
print(V)
    
    
print( "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix ")
MMT <- matrix %*% t(matrix)
print( "this is the result of the multiplication of matrix and t(matrix)" )
print(MMT)
MMT.lamda <- eigen(MMT)
print(MMT.lamda)
U <- -MMT.lamda$vectors
    print("U")
print(U)
    
print("matrix r is the combination of sigular values  ")
R <- sqrt(MMT.lamda$values)
    print(R)  
R = 1/R
R <- R * diag(length(R))
R = matrix (c(R,0,0), nr = 2, nc = 3)    
    
       print("R")
print(R)    
    
pseudo_matrix <- U %*% R %*% t(V)
    
print("#SVD function = U + R + t(V) ")
print("$U ")
print(U)
 print("$R ")
print(R)   
    print("$V")
print(V)
    pseudo_matrix=  t(pseudo_matrix)
    print("# combination of SVD function return the original")
 
return (pseudo_matrix)    
}


In [70]:
print("Matrix C pseudo-inverse step by step")
pseudo_func3(C)

[1] "Matrix C pseudo-inverse step by step"
[1] "find V by using eigenevalue and eigenevector of the multiplication of transpose matrix and matrix "
     [,1] [,2] [,3]
[1,]    2    0    1
[2,]    0    2    0
     [,1] [,2]
[1,]    2    0
[2,]    0    2
[3,]    1    0
[1] "this is the result of the multiplication of transpose matrix and matrix"
     [,1] [,2] [,3]
[1,]    4    0    2
[2,]    0    4    0
[3,]    2    0    1
eigen() decomposition
$values
[1] 5.000000e+00 4.000000e+00 3.552714e-15

$vectors
          [,1] [,2]       [,3]
[1,] 0.8944272    0  0.4472136
[2,] 0.0000000   -1  0.0000000
[3,] 0.4472136    0 -0.8944272

[1] "matrix V is also the combination of eigenevectors of the multiplication of transpose matrix and matrix "
[1] "V"
          [,1] [,2]       [,3]
[1,] 0.8944272    0 -0.4472136
[2,] 0.0000000    1  0.0000000
[3,] 0.4472136    0  0.8944272
[1] "find U by using eigenevalue and eigenevector of the multiplication of matrix and transpose of matrix "
[1] "this is the

[,1] [,2]
[1,] 0.4  0.0 
[2,] 0.0  0.5 
[3,] 0.2  0.0